export const contentArray = [
    "CS", "70", "Discrete", "Mathematics", "and", "Probability", "Theory", 
    "Fall", "2024", "Course", "Notes", "Note", "8",
    "1.", "Polynomials", "Polynomials", "constitute", "a", "rich", 
    "class", "of", "functions", "that", "are", "both", "easy", "to", "describe", 
    "and", "widely", "applicable", "in", "topics", "ranging", "from", "Fourier", 
    "analysis", "cryptography", "and", "communication", "to", "control", "and", 
    "computational", "geometry", "In", "this", "note", "we", "will", "discuss", 
    "further", "properties", "of", "polynomials", "that", "make", "them", "so", 
    "useful", "The", "key", "idea", "here", "is", "to", "extend", "what", "you", 
    "already", "know", "about", "polynomials", "over", "the", "real", "and", 
    "complex", "numbers", "to", "modulo", "arithmetic", "We", "will", "then", 
    "describe", "how", "to", "take", "advantage", "of", "these", "properties", 
    "to", "develop", "a", "secret-sharing", "scheme", "Recall", "that", "a", 
    "polynomial", "in", "a", "single", "variable", "is", "an", "expression", 
    "that", "has", "an", "associated", "function", "The", "polynomial", "expression", 
    "is", "p(x)", "=", "adxd", "+", "ad−1xd−1", "+", "…", "+", "a1x", "+", "a0", 
    "Here", "the", "variable", "x", "and", "the", "coefficients", "ai", "are", 
    "usually", "real", "numbers", "For", "example", "p(x)", "=", "5x3", "+", "2x", 
    "+", "1", "is", "a", "polynomial", "of", "degree", "d", "=", "3", "Its", "coefficients", 
    "are", "a3", "=", "5", "a2", "=", "0", "a1", "=", "2", "and", "a0", "=", "1", "Polynomials", 
    "have", "some", "remarkably", "simple", "elegant", "and", "powerful", "properties", 
    "which", "we", "will", "explore", "in", "this", "note"
  ];
  